### ISSUE TITLE
When I turn on camera it turned on and showing view 90 degrees rotated.

### ISSUE THREAD

**Issue by LakhinaRajat** [livekit/client-sdk-swift#246]
This issue happened when I updated my library with latest main brach 

these are the steps I followed 

it is happening in iOS App

Joined a meeting 
camera settings are 16:9

1. joined a meeting 
2. tuned on the camera
3. camera opened by it is rotated 90 right without rotating the phone.

Please look into it.

https://github.com/livekit/client-sdk-swift/assets/130336875/f0e24e67-bbc7-4835-9866-4e3ddf1560e8

Uploading Screen Recording 2023-09-14 at 2.28.16 PM.mov…

**Comment by LakhinaRajat** [comment]
Please look into it.

**Comment by hiroshihorie** [comment]
Hello, I fixed this one. There will be a new release.

**Comment by LakhinaRajat** [comment]
When is the next release?
when can we expect that?

**Comment by isandeepj** [comment]
@hiroshihorie can you please suggest which older version we can use as of now?

**Comment by isandeepj** [comment]
@hiroshihorie & @cloudwebrtc This issue is still not resolved. 
[114.5735.06](https://github.com/webrtc-sdk/Specs/releases/tag/114.5735.06)

**Comment by hiroshihorie** [comment]
We swapped the WebRTC binary, can you "Reset Package Caches" and try again

**Comment by isandeepj** [comment]
@hiroshihorie still not working for me!

**Comment by hiroshihorie** [comment]
Can you try v1.1.1, please open if still have problems .
